version: '3.9'

services:
  westgenesis-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json